### ISSUE TITLE
Add icon

### ISSUE THREAD

**Issue by hfiguiere** [hfiguiere/gpsami#4]
GPS Ami needs an icon.

**Comment by hfiguiere** [comment]
Proposal (over Twitter)
https://twitter.com/dnlgalleguillos/status/795694892492193794

**Comment by dnlgalleguillos** [comment]
Here you can find a first idea for GPS Ami Icon, I hope you Like. Cheers!!
![gpsami](https://cloud.githubusercontent.com/assets/23320192/20070904/0797abc2-a501-11e6-9371-537400b32623.png)

**Comment by hfiguiere** [comment]
Thanks !
